name: Bug Report
description: Report a bug or issue with GearScoreLite TBC Edition
title: "[Bug] "
labels: ["bug", "triage-needed"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you've checked these items
      options:
        - label: I'm using GearScoreLite **TBC Edition** (not the original)
          required: true
        - label: I'm playing on a **TBC content server** with **WotLK client** (3.3.5a)
          required: true
        - label: I've tried reloading the UI (`/reload`) 
          required: true

  - type: input
    id: addon-version
    attributes:
      label: Addon Version
      description: What version of GearScoreLite TBC Edition are you using?
      placeholder: "e.g., 4.0.1-TBC (check with /gs command)"
    validations:
      required: true

  - type: input
    id: wow-version
    attributes:
      label: WoW Client Version
      description: What WoW client version are you using?
      placeholder: "e.g., 3.3.5a (12340)"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What's the bug? What did you expect to happen vs what actually happened?
      placeholder: "Describe the issue in detail..."
    validations:
      required: true

  - type: textarea
    id: item-examples
    attributes:
      label: Item Examples
      description: If this is about item scoring, please provide specific item names and their scores
      placeholder: |
        Item: [Bristleblitz Striker]
        Item Level: 151
        Expected Score: ~480
        Actual Score: ~290
    validations:
      required: false

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Log into character
        2. Mouse over item [X]
        3. Check score in tooltip
        4. Score shows as Y instead of expected Z
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: "Screenshots, other addons installed, server-specific details, etc."
    validations:
      required: false
